// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Z5X9Apl_EjXBkBh3UPSU4eEO5ersH-s',
    appId: '1:793403757182:web:c802881df094b75ccefe2f',
    messagingSenderId: '793403757182',
    projectId: 'manage-super-orders',
    authDomain: 'manage-super-orders.firebaseapp.com',
    storageBucket: 'manage-super-orders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjuAc4WIyAnUZS0gWY_jFZnwlScOcS960',
    appId: '1:793403757182:android:ef3e425c89ce487bcefe2f',
    messagingSenderId: '793403757182',
    projectId: 'manage-super-orders',
    storageBucket: 'manage-super-orders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrQ8S7xt-lUh60xwuLPL_voAVQ63sZCw',
    appId: '1:793403757182:ios:f1b13d862edd6ba3cefe2f',
    messagingSenderId: '793403757182',
    projectId: 'manage-super-orders',
    storageBucket: 'manage-super-orders.appspot.com',
    iosBundleId: 'com.example.manageOrders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRrQ8S7xt-lUh60xwuLPL_voAVQ63sZCw',
    appId: '1:793403757182:ios:f1b13d862edd6ba3cefe2f',
    messagingSenderId: '793403757182',
    projectId: 'manage-super-orders',
    storageBucket: 'manage-super-orders.appspot.com',
    iosBundleId: 'com.example.manageOrders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Z5X9Apl_EjXBkBh3UPSU4eEO5ersH-s',
    appId: '1:793403757182:web:508248afe0d546eccefe2f',
    messagingSenderId: '793403757182',
    projectId: 'manage-super-orders',
    authDomain: 'manage-super-orders.firebaseapp.com',
    storageBucket: 'manage-super-orders.appspot.com',
  );

}